project:
  type: website
  output-dir: public

website:
  title: "Wastewater Surveillance Platform"
  navbar:
    left:
      - href: trend-report.qmd
        text: Region Reports
        aria-label: Region Reports
      - href: geomatics.qmd
        text: Geomatic
      - href: old-faithful.qmd
        text: Old Faithful
      - href: shinylive.qmd
        text: Shinylive
        
  sidebar:
    - id: trendnav
      title: "Trend Reports"
      style: "docked"
      background: light
      contents: reports/*
      
    - id: geonav
      title: "Geomatics"
      style: "docked"
      background: light
      contents: 
        - gemoatics.qmd
        - other map app
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full



